package scaffold

const workflowHeader = "# Generated by `coverage init`. Review and adjust the test commands for your\n" +
	"# project. Each test job emits coverage-<id>.xml (Cobertura) and tests-<id>.xml\n" +
	"# (JUnit) and uploads them; the report job aggregates them into the run Summary.\n" +
	`name: Coverage

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
`

// reportJob has one %s placeholder for the needs list, e.g. "[test-go, test-web]".
const reportJob = `  report:
    needs: %s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with: { pattern: coverage-*, path: ./cov, merge-multiple: true }
      - uses: actions/download-artifact@v8
        with: { pattern: tests-*, path: ./cov, merge-multiple: true }
      # Pin to a commit SHA (recommended); the action builds from its own source.
      - uses: aanantaco/coverage@<commit-sha>
        with:
          input: ./cov
          output: $GITHUB_STEP_SUMMARY
`

const goJob = `  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with: { go-version: "1.26" }
      - name: Test with coverage
        run: |
          go install gotest.tools/gotestsum@latest
          go install github.com/boumenot/gocover-cobertura@latest
          gotestsum --junitfile tests-go.xml --format pkgname \
            -- -coverprofile=coverage.out -covermode=atomic ./...
          gocover-cobertura < coverage.out > coverage-go.xml
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: coverage-go, path: coverage-go.xml, if-no-files-found: warn }
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: tests-go, path: tests-go.xml, if-no-files-found: warn }
`

const nodeVitestJob = `  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with: { node-version: "22" }
      - run: npm ci
      - name: Test with coverage
        run: |
          npx vitest run --coverage \
            --coverage.reporter=cobertura \
            --reporter=default --reporter=junit \
            --outputFile.junit=tests-web.xml
          cp coverage/cobertura-coverage.xml coverage-web.xml
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: coverage-web, path: coverage-web.xml, if-no-files-found: warn }
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: tests-web, path: tests-web.xml, if-no-files-found: warn }
`

const nodeJestJob = `  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with: { node-version: "22" }
      - run: npm ci
      - name: Test with coverage
        env:
          JEST_JUNIT_OUTPUT_FILE: tests-web.xml
        run: |
          npx jest --coverage --coverageReporters=cobertura \
            --reporters=default --reporters=jest-junit
          cp coverage/cobertura-coverage.xml coverage-web.xml
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: coverage-web, path: coverage-web.xml, if-no-files-found: warn }
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: tests-web, path: tests-web.xml, if-no-files-found: warn }
`

const pythonJob = `  test-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Test with coverage
        run: |
          pip install pytest pytest-cov
          # TODO: set --cov=<your_package>
          pytest --cov=. --cov-report=xml:coverage-py.xml --junitxml=tests-py.xml
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: coverage-py, path: coverage-py.xml, if-no-files-found: warn }
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: tests-py, path: tests-py.xml, if-no-files-found: warn }
`

const rustJob = `  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Test with coverage
        run: |
          cargo install cargo-llvm-cov
          cargo llvm-cov --cobertura --output-path coverage-rust.xml
          # TODO: emit tests-rust.xml (JUnit), e.g. via cargo-nextest with a
          # junit profile. Optional — the Tests column shows a dash without it.
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: coverage-rust, path: coverage-rust.xml, if-no-files-found: warn }
`

const javaJob = `  test-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "21" }
      - name: Test with coverage
        run: |
          # Maven + JaCoCo shown; adapt for Gradle.
          mvn -B test
          # JaCoCo XML is NOT Cobertura — convert it (e.g. cover2cover):
          #   python cover2cover.py target/site/jacoco/jacoco.xml > coverage-java.xml
          # and copy a JUnit report to tests-java.xml:
          #   cp target/surefire-reports/TEST-*.xml tests-java.xml
          # TODO: produce coverage-java.xml (Cobertura) and tests-java.xml (JUnit)
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: coverage-java, path: coverage-java.xml, if-no-files-found: warn }
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: tests-java, path: tests-java.xml, if-no-files-found: warn }
`

const dotnetJob = `  test-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0" }
      - name: Test with coverage
        run: |
          dotnet add package JunitXml.TestLogger
          dotnet test \
            --collect:"XPlat Code Coverage" \
            --logger "junit;LogFilePath=tests-dotnet.xml" \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
          cp "$(find . -name coverage.cobertura.xml | head -1)" coverage-dotnet.xml
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: coverage-dotnet, path: coverage-dotnet.xml, if-no-files-found: warn }
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: tests-dotnet, path: tests-dotnet.xml, if-no-files-found: warn }
`

const coverageIgnore = `# Paths excluded from aggregated coverage. Gitignore syntax, repo-root-relative.
# Generated by ` + "`coverage init`" + ` — adjust for your project.

# Generated code / build output
**/dist/**
**/build/**
**/.next/**

# Test files
**/*_test.go
**/*.test.ts
**/*.test.tsx
**/*.spec.ts

# Vendored / third-party
**/node_modules/**
**/vendor/**

# Non-unit-testable glue
**/cmd/**
**/testutil/**
`

const coverageYAML = `# coverage.yaml — optional; the tool works with zero config. Uncomment and adjust.
# Full annotated schema:
# https://github.com/aanantaco/coverage/blob/main/coverage.yaml.example

# folder_group_depth: 3
# display_from: id            # or "shared-slash"

# baseline:
#   path: coverage-summary.json
#   # fail_on_drop: 0.5

# workspaces:
#   <id>:
#     display_name: services/<id>
#     prefix: services/<id>/
#     # strip_prefix: github.com/acme/repo/services/<id>/
`
