package scaffold

import "fmt"

const workflowHeader = "# Generated by `coverage init`. The report job is ready to use; fill in each\n" +
	"# test job's TODO with your project's test command (see the linked docs), so\n" +
	"# it emits coverage-<id>.xml (Cobertura) and tests-<id>.xml (JUnit).\n" +
	`name: Coverage

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
`

// stubJob returns a minimal, framework-agnostic test job: it checks out, leaves
// a TODO pointing at the per-language docs for the actual test command, and
// uploads the two artifacts the report job consumes. Deliberately free of
// version-pinned framework commands so it does not rot.
func stubJob(l Language) string {
	return fmt.Sprintf(`  %[2]s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # TODO: run your %[1]s tests so they produce coverage-%[3]s.xml (Cobertura)
      #       and tests-%[3]s.xml (JUnit). Commands:
      #       https://github.com/aanantaco/coverage/blob/main/docs/%[4]s
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: coverage-%[3]s, path: coverage-%[3]s.xml, if-no-files-found: warn }
      - uses: actions/upload-artifact@v7
        if: always()
        with: { name: tests-%[3]s, path: tests-%[3]s.xml, if-no-files-found: warn }
`, l.Name, l.JobName, l.ID, l.Doc)
}

// reportJob has one %s placeholder for the needs list, e.g. "[test-go, test-web]".
const reportJob = `  report:
    needs: %s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with: { pattern: coverage-*, path: ./cov, merge-multiple: true }
      - uses: actions/download-artifact@v8
        with: { pattern: tests-*, path: ./cov, merge-multiple: true }
      # Pin to a commit SHA (recommended); the action builds from its own source.
      - uses: aanantaco/coverage@<commit-sha>
        with:
          input: ./cov
          output: $GITHUB_STEP_SUMMARY
`

const coverageIgnore = `# Paths excluded from aggregated coverage. Gitignore syntax, repo-root-relative.
# Generated by ` + "`coverage init`" + ` — adjust for your project.

# Generated code / build output
**/dist/**
**/build/**
**/.next/**

# Test files
**/*_test.go
**/*.test.ts
**/*.test.tsx
**/*.spec.ts

# Vendored / third-party
**/node_modules/**
**/vendor/**

# Non-unit-testable glue
**/cmd/**
**/testutil/**
`

const coverageYAML = `# coverage.yaml — optional; the tool works with zero config. Uncomment and adjust.
# Full annotated schema:
# https://github.com/aanantaco/coverage/blob/main/coverage.yaml.example

# folder_group_depth: 3
# display_from: id            # or "shared-slash"

# baseline:
#   path: coverage-summary.json
#   # fail_on_drop: 0.5

# workspaces:
#   <id>:
#     display_name: services/<id>
#     prefix: services/<id>/
#     # strip_prefix: github.com/acme/repo/services/<id>/
`
